### ISSUE TITLE
How can I make this script use my own .eslintrc?

### ISSUE THREAD

**Issue by AndrzejT** [stevejhiggs/gulp-webpack-es6-pipeline#2]
I'm getting hundreds trivial of errors like:
...
 230:33   warning  Unexpected unnamed function                                                    func-names
 230:41   error    There should be no spaces inside this paren                                    space-in-parens
 230:41   error    Missing space before function parentheses                                      space-before-function-paren
 231:9    error    Opening curly brace does not appear on the same line as controlling statement  brace-style
 232:13   error    Expected exception block, space or tab after '//' in comment                   spaced-comment
 233:13   error    Expected indentation of 10 spaces but found 12                                 indent
...

I guess I can avoid it just by setting my own .eslintrc, but it seems it is ignored.... ?

**Comment by stevejhiggs** [comment]
This package intentionally uses the common airbnb linting standards from https://www.npmjs.com/package/eslint-config-airbnb

There are no plans to let you use your own linting rules. Feel free to fork the package or use the code as a base for your own custom version though

**Comment by stevejhiggs** [comment]
This is now possible in v9. The readme details how to do it.
